name: Sync Vless Worker Script

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 * * * *' # 每小时运行一次 (UTC 时间)，您可以根据需要调整

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 确保拉取完整历史，以便 git diff 更准确地工作

      - name: Download and prepare script
        id: download_script # 添加 ID 以便后续步骤引用
        run: |
          RAW_FILE_URL="https://raw.githubusercontent.com/yonggekkk/Cloudflare-vless-trojan/refs/heads/main/Vless_workers_pages/vless无需proxyip的nat64套壳版 (推荐使用).js"
          LOCAL_FILE_PATH="Vless_workers_pages/vless无需proxyip的nat64套壳版 (推荐使用).js"

          echo "Attempting to create directory: $(dirname "$LOCAL_FILE_PATH")"
          mkdir -p "$(dirname "$LOCAL_FILE_PATH")"
          if [ $? -ne 0 ]; then
            echo "Error: Failed to create directory!"
            exit 1
          fi
          echo "Directory created or already exists."

          echo "Attempting to download file from: $RAW_FILE_URL"
          wget -O "$LOCAL_FILE_PATH" "$RAW_FILE_URL"
          if [ $? -ne 0 ]; then
            echo "Error: Failed to download file from $RAW_FILE_URL"
            exit 1
          fi
          echo "File downloaded successfully to $LOCAL_FILE_PATH"

          # 检查文件是否存在且不为空
          if [ ! -s "$LOCAL_FILE_PATH" ]; then
            echo "Error: Downloaded file is empty or does not exist locally."
            exit 1
          fi

          # 检查是否有文件更改，并将结果传递给下一步
          if git diff --quiet "$LOCAL_FILE_PATH"; then
            echo "No changes detected in $LOCAL_FILE_PATH. Skipping commit."
            echo "changes_detected=false" >> "$GITHUB_OUTPUT"
          else
            echo "Changes detected in $LOCAL_FILE_PATH. Proceeding with commit."
            echo "changes_detected=true" >> "$GITHUB_OUTPUT"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 确保此步骤可以使用token

      - name: Commit and push if changes detected
        if: steps.download_script.outputs.changes_detected == 'true' # 只有当检测到变化时才执行
        run: |
          LOCAL_FILE_PATH="Vless_workers_pages/vless无需proxyip的nat64套壳版 (推荐使用).js"

          echo "Configuring Git user."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          echo "Git user configured."

          echo "Adding $LOCAL_FILE_PATH to staging area."
          git add "$LOCAL_FILE_PATH"
          if [ $? -ne 0 ]; then
            echo "Error: Failed to add file to Git staging area."
            exit 1
          fi
          echo "File added."

          echo "Attempting to commit changes."
          # 使用 --allow-empty-message 和 --no-edit 可以避免一些非预期行为
          git commit -m "chore: Auto sync Vless worker script"
          if [ $? -ne 0 ]; then
            echo "Warning: Git commit failed, likely no changes to commit. Proceeding to push."
            # 如果是第一次下载，或者文件被删除后重新下载，则 commit 一定会成功
            # 如果文件内容完全一致，这里可能会失败，但我们仍尝试 push
          fi
          echo "Changes committed."

          echo "Attempting to push changes to repository."
          git push
          if [ $? -ne 0 ]; then
            echo "Error: Failed to push changes to GitHub."
            exit 1
          fi
          echo "Changes pushed successfully!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
