name: Sync Vless Worker Script

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 * * * *' # 每小时运行一次，您可以根据需要调整，例如 '0 0 * * *' 表示每天运行一次

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and update script
        run: |
          # 定义要下载的原始文件 URL
          RAW_FILE_URL="https://raw.githubusercontent.com/yonggekkk/Cloudflare-vless-trojan/refs/heads/main/Vless_workers_pages/vless无需proxyip的nat64套壳版 (推荐使用).js"
          # 定义本地保存的文件路径和名称
          LOCAL_FILE_PATH="Vless_workers_pages/vless无需proxyip的nat64套壳版 (推荐使用).js"

          # 创建目录（如果不存在）
          mkdir -p $(dirname "$LOCAL_FILE_PATH")

          # 下载文件
          wget -O "$LOCAL_FILE_PATH" "$RAW_FILE_URL"

          # 检查文件是否有更改
          git diff --exit-code "$LOCAL_FILE_PATH" || \
          (
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add "$LOCAL_FILE_PATH"
            git commit -m "chore: Auto sync Vless worker script"
            git push
          )
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
